version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing source NPM dependencies...
      - npm install

  pre_build:
    commands:
      - echo Pre-build phase...
  
  build:
    commands:
      - echo Build started on `date`
      - npm run build # (if you have a build script, otherwise you can skip this)

  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Running tests..."
      - npm test # (if you have tests defined)

artifacts:
  files:
    - '**/*'
  base-directory: . # (or specify your build output directory)
